"""add sudo_rndc flag

Revision ID: 228cf4e085a3
Revises: 50270f838448
Create Date: 2026-08-06 06:40:52.198692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228cf4e085a3'
down_revision = '50270f838448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_servers', schema=None) as batch_op:
        # server_default обязателен: в таблице уже есть строка с настроенной УЗ.
        batch_op.add_column(sa.Column('sudo_rndc', sa.Boolean(),
                                      nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_servers', schema=None) as batch_op:
        batch_op.drop_column('sudo_rndc')

    # ### end Alembic commands ###
