"""initial schema

Revision ID: 4380e11e3ec1
Revises: 
Create Date: 2026-06-19 11:15:18.434214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4380e11e3ec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssh_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=False),
    sa.Column('zone_file_path', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('entries_found', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_uploaded_at'), ['uploaded_at'], unique=False)

    op.create_table('rpz_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_by', sa.Integer(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fetched_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['ssh_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rpz_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rpz_snapshots_fetched_at'), ['fetched_at'], unique=False)

    op.create_table('block_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('block_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_entries_value'), ['value'], unique=True)

    op.create_table('rpz_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=500), nullable=False),
    sa.Column('is_wildcard', sa.Boolean(), nullable=False),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['rpz_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rpz_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rpz_entries_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_rpz_entries_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rpz_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rpz_entries_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_rpz_entries_domain'))

    op.drop_table('rpz_entries')
    with op.batch_alter_table('block_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_entries_value'))

    op.drop_table('block_entries')
    with op.batch_alter_table('rpz_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rpz_snapshots_fetched_at'))

    op.drop_table('rpz_snapshots')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_uploaded_at'))

    op.drop_table('documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('ssh_servers')
    # ### end Alembic commands ###
