"""url entries, push logs, push safety fields

Revision ID: 50270f838448
Revises: c50f8aaf8e63
Create Date: 2026-08-06 05:28:44.649526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50270f838448'
down_revision = 'c50f8aaf8e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entries_count', sa.Integer(), nullable=False),
    sa.Column('domains', sa.Text(), nullable=True),
    sa.Column('backup_path', sa.String(length=500), nullable=True),
    sa.Column('old_serial', sa.String(length=32), nullable=True),
    sa.Column('new_serial', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['ssh_servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_logs_started_at'), ['started_at'], unique=False)

    op.create_table('url_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=False),
    sa.Column('host', sa.String(length=500), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    with op.batch_alter_table('url_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_entries_host'), ['host'], unique=False)

    with op.batch_alter_table('block_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pushed_at', sa.DateTime(), nullable=True))

    # server_default обязателен: на боевом сервере в таблице уже есть строка с УЗ,
    # без значения по умолчанию добавление NOT NULL-колонки завершилось бы ошибкой.
    with op.batch_alter_table('ssh_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_name', sa.String(length=255),
                                      nullable=False, server_default='rpz.block'))
        batch_op.add_column(sa.Column('use_sudo', sa.Boolean(),
                                      nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('validate_zone', sa.Boolean(),
                                      nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('reload_zone', sa.Boolean(),
                                      nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_servers', schema=None) as batch_op:
        batch_op.drop_column('reload_zone')
        batch_op.drop_column('validate_zone')
        batch_op.drop_column('use_sudo')
        batch_op.drop_column('zone_name')

    with op.batch_alter_table('block_entries', schema=None) as batch_op:
        batch_op.drop_column('pushed_at')

    with op.batch_alter_table('url_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_entries_host'))

    op.drop_table('url_entries')
    with op.batch_alter_table('push_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_logs_started_at'))

    op.drop_table('push_logs')
    # ### end Alembic commands ###
