"""letters storage, vt reports, app settings, manual source

Revision ID: b947ab6b927b
Revises: 228cf4e085a3
Create Date: 2026-08-07 04:55:53.256025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b947ab6b927b'
down_revision = '228cf4e085a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('vt_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('malicious', sa.Integer(), nullable=False),
    sa.Column('suspicious', sa.Integer(), nullable=False),
    sa.Column('harmless', sa.Integer(), nullable=False),
    sa.Column('undetected', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('total_engines', sa.Integer(), nullable=False),
    sa.Column('permalink', sa.String(length=500), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('checked_by', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vt_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vt_reports_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vt_reports_value'), ['value'], unique=True)

    with op.batch_alter_table('block_entries', schema=None) as batch_op:
        # server_default обязателен: в таблице уже есть записи из писем.
        batch_op.add_column(sa.Column('source', sa.String(length=20),
                                      nullable=False, server_default='letter'))
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('letter_number', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('letter_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('stored_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pdf_stored_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pdf_original_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pdf_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('pdf_size')
        batch_op.drop_column('pdf_original_name')
        batch_op.drop_column('pdf_stored_name')
        batch_op.drop_column('file_size')
        batch_op.drop_column('content_type')
        batch_op.drop_column('stored_name')
        batch_op.drop_column('letter_date')
        batch_op.drop_column('letter_number')

    with op.batch_alter_table('block_entries', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('source')

    with op.batch_alter_table('vt_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vt_reports_value'))
        batch_op.drop_index(batch_op.f('ix_vt_reports_checked_at'))

    op.drop_table('vt_reports')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
