"""add ioc_hashes table

Revision ID: c50f8aaf8e63
Revises: 4380e11e3ec1
Create Date: 2026-06-22 05:59:31.067316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50f8aaf8e63'
down_revision = '4380e11e3ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ioc_hashes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('hash_type', sa.String(length=10), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ioc_hashes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ioc_hashes_value'), ['value'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ioc_hashes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ioc_hashes_value'))

    op.drop_table('ioc_hashes')
    # ### end Alembic commands ###
